version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: super_secret
      POSTGRES_USER: app
      POSTGRES_DB: neighbourify
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
  app:
    build: .
    command: bash -c "python manage.py makemigrations  && python manage.py migrate && python manage.py runserver 0.0.0.0:8990"
    volumes:
      - .:/app
    ports:
      - "8990:8990"
    depends_on:
      - postgres
    restart: always
